NameVirtualHost *:443
<VirtualHost *:443>
	ServerAdmin webmaster@localhost
	ServerName localhost
	DocumentRoot "/opt/lampp/htdocs/localhost/www"
	ScriptAlias /cgi/ "/opt/lampp/htdocs/localhost/cgi/
	ErrorLog /opt/lampp/htdocs/localhost/error.log
	CustomLog /opt/lampp/htdocs/localhost/access.log common
        SSLEngine on
        SSLCertificateFile "/opt/lampp/etc/ssl.crt/server.crt"
        SSLCertificateKeyFile "/opt/lampp/etc/ssl.key/server.key"
</VirtualHost>

#<VirtualHost *:80>
#	ServerAdmin webmaster@ssl.lan
#	ServerName ssl.lan
#	DocumentRoot "/opt/lampp/htdocs/ssl.lan/www"
#	ScriptAlias /cgi/ "/opt/lampp/htdocs/ssl.lan/cgi/
#	ErrorLog /opt/lampp/htdocs/ssl.lan/error.log
#	CustomLog /opt/lampp/htdocs/ssl.lan/access.log common
#</VirtualHost>


<VirtualHost *:443>
    DocumentRoot "/opt/lampp/htdocs/ssl.lan/www"
    ServerName ssl.lan
    ScriptAlias /cgi/ "/opt/lampp/htdocs/ssl.lan/cgi/
    ErrorLog /opt/lampp/htdocs/ssl.lan/error.log
    CustomLog /opt/lampp/htdocs/ssl.lan/access.log common
    SSLEngine on
    #SSLCertificateFile "conf/ssl.crt/server.crt"
    SSLCertificateFile "/opt/lampp/etc/ssl.crt/server.crt"
    #SSLCertificateKeyFile "conf/ssl.key/server.key"
    SSLCertificateKeyFile "/opt/lampp/etc/ssl.key/server.key"
</VirtualHost>

<VirtualHost *:443>
    DocumentRoot "/opt/lampp/htdocs/huggingface.co/www"
    ServerName huggingface.co
    ScriptAlias /cgi/ "/opt/lampp/htdocs/huggingface.co/cgi/
    ErrorLog /opt/lampp/htdocs/huggingface.co/error.log
    CustomLog /opt/lampp/htdocs/huggingface.co/access.log common
    SSLEngine on
    #SSLCertificateFile "conf/ssl.crt/server.crt"
    SSLCertificateFile "/opt/lampp/etc/ssl.crt/fastxampp.crt"
    #SSLCertificateKeyFile "conf/ssl.key/server.key"
    SSLCertificateKeyFile "/opt/lampp/etc/ssl.key/fastxampp.key"
</VirtualHost>
